# Generated by Django 4.2.30 on 2026-06-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_cuentacaja_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contribuyente', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioConsultora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(max_length=50)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contador', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cliente')),
            ],
        ),
    ]
