# Generated by Django 4.2.30 on 2026-06-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_cliente_servicioconsultora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado')], default='VIGENTE', max_length=20)),
                ('carga_horaria', models.IntegerField(default=0, help_text='Cantidad de horas')),
                ('honorario_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_anticipo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
            ],
        ),
    ]
