# Generated by Django 4.2.30 on 2026-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_empleado_pagosueldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='comision',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='forma_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='vendedor',
            field=models.CharField(default='Administración', max_length=100),
        ),
    ]
