# Generated by Django 4.2.30 on 2026-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_remove_inscripcion_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
    ]
