# Generated by Django 4.2.30 on 2026-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='modalidad',
            field=models.CharField(default='VIRTUAL', max_length=50),
        ),
    ]
