# Generated by Django 4.2.30 on 2026-06-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_inscripcion_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='curso',
            name='antiguos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='observaciones',
            field=models.CharField(blank=True, default='PROGRAMADO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='promo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academico.docente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inversion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
