# Generated by Django 4.2.30 on 2026-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_remove_curso_modalidad_curso_antiguos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
