# Generated by Django 4.2.30 on 2026-06-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_curso_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='observaciones',
        ),
    ]
