# Generated by Django 4.2.30 on 2026-06-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_remove_curso_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='honorario',
            old_name='fecha_anticipo',
            new_name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='honorario_total',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='observacion',
        ),
        migrations.AddField(
            model_name='honorario',
            name='monto_acordado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='honorario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
