# Generated by Django 4.2.30 on 2026-06-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_rename_fecha_anticipo_honorario_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='carga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='fecha_anticipo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='modo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='realizado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='monto_acordado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
