# Generated by Django 4.2.30 on 2026-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_honorario_carga_honorario_fecha_anticipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioconsultora',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='contador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
