# Generated by Django 4.2.30 on 2026-06-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_servicioconsultora_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
    ]
