# Generated by Django 4.2.30 on 2026-06-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_honorario_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('CERTIFICADO', 'CERTIFICADO'), ('GRABACIÓN', 'GRABACIÓN'), ('SISTEMA', 'SISTEMA'), ('OTRO', 'OTRO')], max_length=50)),
                ('detalle', models.CharField(help_text='Ej: Certificado de Excel Básico, Sistema de Asistencia...', max_length=250)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('vendedor', models.CharField(max_length=100)),
                ('registrado_por', models.CharField(max_length=100)),
                ('fecha_venta', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_servicios', to='academico.participante')),
            ],
            options={
                'verbose_name': 'Venta de Servicio',
                'verbose_name_plural': 'Ventas de Servicios',
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
    ]
