# Generated by Django 4.2.30 on 2026-06-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_ventaservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaservicio',
            name='detalle',
            field=models.CharField(blank=True, help_text='Ej: Certificado de...', max_length=250, null=True),
        ),
    ]
