# Generated by Django 4.2.30 on 2026-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosueldo',
            name='aportes_afp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='bono_antiguedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='bono_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='otros_bonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='otros_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='rc_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
