# Generated by Django 4.2.30 on 2026-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_pagosueldo_aportes_afp_pagosueldo_bono_antiguedad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosueldo',
            old_name='bonos',
            new_name='anticipos',
        ),
        migrations.RenameField(
            model_name='pagosueldo',
            old_name='descuentos',
            new_name='bono_consultora',
        ),
        migrations.RenameField(
            model_name='pagosueldo',
            old_name='otros_descuentos',
            new_name='comisiones_certificados',
        ),
        migrations.RemoveField(
            model_name='pagosueldo',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='multas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='pasanaku',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='prestamos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagosueldo',
            name='rendicion_cuentas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagosueldo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
