# Generated by Django 4.2.30 on 2026-06-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_rename_bonos_pagosueldo_anticipos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=50, verbose_name='Número de NIT')),
                ('nro_ministerio', models.CharField(max_length=100, verbose_name='Nº Identificador Ministerio de Trabajo')),
                ('nro_caja_salud', models.CharField(max_length=50, verbose_name='Nº de Empleador (Caja de Salud)')),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
            },
        ),
    ]
