# Generated by Django 4.2.30 on 2026-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_datosempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Haber Básico Acordado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo (F/M)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=150, verbose_name='Ocupación que desempeña'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ci',
            field=models.CharField(max_length=20, verbose_name='Documento de Identidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(max_length=200, verbose_name='Apellidos y Nombres'),
        ),
    ]
