# Generated by Django 4.2.30 on 2026-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_alter_empleado_options_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='denominacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domicilio_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_contribuyente',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
    ]
