# Generated by Django 4.2.30 on 2026-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_alter_cliente_options_cliente_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconsultora',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='Archivo de Factura'),
        ),
    ]
