# Generated by Django 4.2.30 on 2026-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_servicioconsultora_archivo_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre del Contador(a)')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
            },
        ),
        migrations.RemoveField(
            model_name='servicioconsultora',
            name='contador',
        ),
    ]
