# Generated by Django 4.2.30 on 2026-06-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_contador_remove_servicioconsultora_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconsultora',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.contador', verbose_name='Contador Asignado'),
        ),
    ]
