# Generated by Django 4.2.30 on 2026-06-17 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_servicioconsultora_contador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=datetime.date.today)),
                ('tipo_prestamo', models.CharField(default='AMORTIZABLE', max_length=50)),
                ('tipo_cuota', models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('MENSUAL', 'MENSUAL')], max_length=50)),
                ('dia_de_pago', models.CharField(help_text='Ej: DOMINGO, DÍA 15 DEL MES', max_length=100)),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nro_cuotas', models.IntegerField(default=1)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_adquiridos', to='academico.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='PagoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_descuento_planilla', models.BooleanField(default=False, help_text='¿Se descontó del sueldo?')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='academico.prestamo')),
            ],
            options={
                'verbose_name': 'Pago de Préstamo',
                'verbose_name_plural': 'Pagos de Préstamos',
            },
        ),
    ]
