# Generated by Django 4.2.30 on 2026-06-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0027_prestamo_pagoprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioconsultora',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.cliente', verbose_name='Cliente'),
        ),
    ]
