# Generated by Django 4.2.30 on 2026-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_alter_servicioconsultora_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='registrado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
