# Generated by Django 4.2.30 on 2026-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0029_inscripcion_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_publicidad',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/'),
        ),
    ]
