# Generated by Django 4.2.30 on 2026-06-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0030_curso_imagen_publicidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.CharField(choices=[('ADMINISTRACION', 'Administración (Efectivo)'), ('CAJA_CHICA', 'Caja Chica (Efectivo)'), ('GERENCIA', 'Gerencia (Efectivo)'), ('AHORRO', 'Ahorro (Efectivo)'), ('BANCO', 'Banco (Extracto)')], max_length=50)),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_fisico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
