# Generated by Django 4.2.30 on 2026-06-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0031_arqueocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.participante'),
        ),
    ]
