# Generated by Django 4.2.30 on 2026-06-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_alter_honorario_curso_alter_inscripcion_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='celular_externo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular (Externo)'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre_externo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre (Externo)'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.empleado'),
        ),
    ]
