# Generated by Django 4.2.30 on 2026-07-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0033_prestamo_celular_externo_prestamo_nombre_externo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaConsultora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
