# Generated by Django 4.2.30 on 2026-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0034_citaconsultora'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaconsultora',
            name='modalidad',
            field=models.CharField(default='PRESENCIAL', max_length=50),
        ),
    ]
