# Generated by Django 4.2.30 on 2026-07-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0035_citaconsultora_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('FACTURAS', 'Facturas Emitidas'), ('FORMULARIOS', 'Formularios y Declaraciones'), ('PLANILLAS', 'Planillas Impositivas'), ('OTROS', 'Otros Documentos')], max_length=50)),
                ('enlace_drive', models.URLField(max_length=800)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
