# Generated by Django 4.2.30 on 2026-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0036_archivodigital'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificados_enviados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_envio_certificados',
            field=models.DateField(blank=True, null=True),
        ),
    ]
