# Generated by Django 4.2.30 on 2026-07-03 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_curso_certificados_enviados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('mes_descuento', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.cuentacaja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.empleado')),
            ],
            options={
                'verbose_name': 'Anticipo de Sueldo',
                'verbose_name_plural': 'Anticipos de Sueldo',
            },
        ),
    ]
