# Generated by Django 4.2.30 on 2026-07-04 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0038_anticipoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosueldo',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.cuentacaja'),
        ),
        migrations.AlterField(
            model_name='anticipoempleado',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.cuentacaja'),
        ),
    ]
