# Generated by Django 4.2.30 on 2026-07-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0039_pagosueldo_cuenta_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modulo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcursos', to='academico.curso'),
        ),
    ]
