# Generated by Django 4.2.30 on 2026-07-12 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0040_curso_modulo_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], max_length=20)),
                ('estado', models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('FALTA', 'Falta')], default='PUNTUAL', max_length=20)),
                ('minutos_retraso', models.IntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_laborales', to='academico.empleado')),
            ],
            options={
                'verbose_name': 'Asistencia de Empleado',
                'verbose_name_plural': 'Asistencias de Empleados',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
