# Generated by Django 4.2.30 on 2026-07-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0041_asistenciaempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codigo_rfid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Tarjeta RFID'),
        ),
    ]
