# Generated by Django 4.2.30 on 2026-07-13 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0042_empleado_codigo_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dias_laborales',
            field=models.CharField(default='L,M,X,J,V', max_length=50, verbose_name='Días Laborales'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_ingreso',
            field=models.TimeField(default=datetime.time(8, 30), verbose_name='Hora de Ingreso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_salida',
            field=models.TimeField(default=datetime.time(18, 30), verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tolerancia_minutos',
            field=models.IntegerField(default=10, verbose_name='Tolerancia (minutos)'),
        ),
    ]
