# Generated by Django 4.2.30 on 2026-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0043_empleado_dias_laborales_empleado_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dias_laborales',
            field=models.CharField(default='L,M,X,J,V', help_text='Ej: L,M,X,J,V,S', max_length=50, verbose_name='Días Laborales'),
        ),
    ]
