# Generated by Django 4.2.30 on 2026-07-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0044_alter_empleado_dias_laborales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='cuenta',
            field=models.CharField(choices=[('ADMINISTRACION', 'Administración (Efectivo)'), ('CAJA_CHICA', 'Caja Chica (Efectivo)'), ('GERENCIA', 'Gerencia (Efectivo)'), ('AHORRO', 'Ahorro (Efectivo)'), ('BANCO', 'Banco (Extracto)'), ('SALUD', 'Salud (Extracto)'), ('RESERVA', 'Reserva (Extracto)'), ('DOLARES', 'Dólares (Efectivo USD)')], max_length=50),
        ),
    ]
