# Generated by Django 4.2.30 on 2026-07-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0045_alter_arqueocaja_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconsultora',
            name='cliente_expreso_nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicioconsultora',
            name='cliente_expreso_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicioconsultora',
            name='es_cliente_expreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicioconsultora',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.cliente', verbose_name='Cliente'),
        ),
    ]
