# Generated by Django 4.2.30 on 2026-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0046_servicioconsultora_cliente_expreso_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodigital',
            name='categoria',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='archivodigital',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
