# Generated by Django 4.2.30 on 2026-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0047_alter_archivodigital_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_contenido',
            field=models.ImageField(blank=True, null=True, upload_to='contenidos/'),
        ),
    ]
