# Generated by Django 4.2.30 on 2026-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0048_curso_imagen_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='publicado_en_redes',
            field=models.BooleanField(default=False),
        ),
    ]
