# Generated by Django 4.2.30 on 2026-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0049_curso_publicado_en_redes'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
