# Generated by Django 4.2.30 on 2026-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0050_participante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ci',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carnet de Identidad'),
        ),
    ]
