# Generated by Django 4.2.30 on 2026-07-30 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0052_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosueldo',
            old_name='comisiones_certificados',
            new_name='bono_whatsapp',
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_revision_whatsapp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='revisado_por_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_revisados', to='academico.empleado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='whatsapp_revisado',
            field=models.BooleanField(default=False),
        ),
    ]
