# Generated by Django 4.2.30 on 2026-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0053_rename_comisiones_certificados_pagosueldo_bono_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('FALTA', 'Falta'), ('PERMISO', 'Permiso'), ('DESCANSO', 'Descanso'), ('COMISION', 'Comisión'), ('VACACIONES', 'Vacaciones'), ('CESANTIA', 'Cesantía')], default='PUNTUAL', max_length=20),
        ),
    ]
