# Generated by Django 4.2.30 on 2026-07-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0055_alter_asistenciaempleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosueldo',
            name='comision_certificados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
