# Generated by Django 4.2.30 on 2026-08-17 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0056_pagosueldo_comision_certificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
