# Generated by Django 4.2.30 on 2026-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0057_alter_asistenciaempleado_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosueldo',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
